# This is a basic workflow to help you get started with Actions

name: Tranfer Image

# Controls when the workflow will run
on:
  release:
    types: [published]
env:
  REGISTRY_USER: ${{ secrets.USERNAME }}
  IMAGE_REGISTRY: registry.cn-shanghai.aliyuncs.com
  REGISTRY_PASSWORD: ${{ secrets.PASSWORD }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Echo
        run: echo images.txt
        
      - uses: redhat-actions/podman-login@v1
        name: Run push
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: Run Push
        run: bash action.sh images.txt
